# Generated by Django 4.1.7 on 2023-02-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название'),
        ),
    ]
