# Generated by Django 4.1.7 on 2023-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0004_realestate_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='seller',
            field=models.CharField(default='', max_length=300),
        ),
    ]
